nelmio_api_doc:
    documentation:
        info:
            title: CardPlayer API 
            description: Une API de distribution et de jeu de carte
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
