vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /pictures/img
            upload_destination: '%kernel.project_dir%/public/assets/pictures'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
